# Generated by Django 2.2 on 2021-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210729_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='link',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(max_length=254),
        ),
    ]
